
"""
Notebook Templates v5.0 — Environment-Specific Cells
=====================================================
Each cell is defined as a list of strings (one per line).
Environment-specific cells are stored in dicts keyed by 'colab', 'kaggle', 'lightning'.
Shared cells are plain lists.
"""

# =====================================================================
# MARKDOWN HEADER
# =====================================================================
MARKDOWN_HEADER = [
    "# 🧱 LEGO Recognition Pipeline (Strategy C)\n",
    "**Automated Setup** – This notebook is pre-configured for **{env_label}**.\n",
    "\n",
    "---"
]

# =====================================================================
# CELL 0: SETUP (Environment-Specific)
# =====================================================================

# --- SHARED IMPORTS & COMMON TAIL (appended after env-specific block) ---
_C0_IMPORTS = [
    "import os, sys, shutil, json, zipfile, urllib.request, logging, subprocess, torch, psutil\n",
    "from pathlib import Path\n",
    "\n",
    "PROJECT_ROOT = ''\n",
    "WORKSPACE_DIR = ''\n",
    "DATASET_DIR = ''\n",
    "LOG_FILE_PATH = ''\n",
    "LDRAW_PATH = '/tmp/ldraw'\n",
    "ADDON_PATH = '/tmp'\n",
    "BLENDER_PATH = 'blender'\n",
    "\n",
]

_C0_COMMON_TAIL = [
    "\n",
    "os.system('pip install ultralytics pandas requests scikit-learn psutil ipywidgets pyyaml faiss-cpu google-api-python-client google-auth-oauthlib -q')\n",
    "\n",
    "if PROJECT_ROOT and PROJECT_ROOT not in sys.path: sys.path.insert(0, PROJECT_ROOT)\n",
"\n",
"try:\n",
"    os.makedirs(WORKSPACE_DIR, exist_ok=True)\n",
"    DATASET_DIR = os.path.join(WORKSPACE_DIR, 'datasets')\n",
"    os.makedirs(DATASET_DIR, exist_ok=True)\n",
"except PermissionError:\n",
"    print(f'❌ ERROR PERMISOS: No se pudo crear el workspace en {WORKSPACE_DIR}')\n",
"    WORKSPACE_DIR = os.path.join(os.getcwd(), 'workspace_emergency_fallback')\n",
"    DATASET_DIR = os.path.join(WORKSPACE_DIR, 'datasets')\n",
"    os.makedirs(DATASET_DIR, exist_ok=True)\n",
"    print(f'📍 Reubicado: {WORKSPACE_DIR}')\n",
"\n",
    "LOG_FILE_PATH = os.path.join(WORKSPACE_DIR, 'pipeline_exec.log')\n",
    "logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s',\n",
    "                    handlers=[logging.FileHandler(LOG_FILE_PATH, mode='w')])\n",
    "logger = logging.getLogger('LegoVision')\n",
    "\n",
    "class StreamToLogger(object):\n",
    "    def __init__(self, logger, original_stream, level=logging.INFO):\n",
    "        self.logger = logger\n",
    "        self.original_stream = original_stream\n",
    "        self.level = level\n",
    "        self._in_write = False\n",
    "    def write(self, buf):\n",
    "        if self._in_write: return self.original_stream.write(buf)\n",
    "        self._in_write = True\n",
    "        try:\n",
    "            content = buf.rstrip()\n",
    "            if content:\n",
    "                for line in content.splitlines():\n",
    "                    self.logger.log(self.level, line.rstrip())\n",
    "            self.original_stream.write(buf)\n",
    "        finally:\n",
    "            self._in_write = False\n",
    "    def flush(self): self.original_stream.flush()\n",
    "\n",
    "if not isinstance(sys.stdout, StreamToLogger):\n",
    "    sys.stdout = StreamToLogger(logger, sys.stdout, logging.INFO)\n",
    "if not isinstance(sys.stderr, StreamToLogger):\n",
    "    sys.stderr = StreamToLogger(logger, sys.stderr, logging.ERROR)\n",
    "\n",
    "import threading, time\n",
    "class HardwareMonitor:\n",
    "    def __init__(self, interval=15):\n",
    "        self.interval = interval\n",
    "        self.running = False\n",
    "        self.metrics = []\n",
    "        self.thread = None\n",
    "    def _monitor_loop(self):\n",
    "        while self.running:\n",
    "            m = {\n",
    "                'time': time.strftime('%Y-%m-%d %H:%M:%S'),\n",
    "                'cpu': psutil.cpu_percent(),\n",
    "                'ram': psutil.virtual_memory().percent\n",
    "            }\n",
    "            if torch.cuda.is_available():\n",
    "                m['gpu_alloc'] = torch.cuda.memory_allocated() / 1e9\n",
    "                m['gpu_resv'] = torch.cuda.memory_reserved() / 1e9\n",
    "            self.metrics.append(m)\n",
    "            time.sleep(self.interval)\n",
    "    def start(self):\n",
    "        self.running = True\n",
    "        self.thread = threading.Thread(target=self._monitor_loop, daemon=True)\n",
    "        self.thread.start()\n",
    "    def stop(self, out_path):\n",
    "        self.running = False\n",
    "        if self.thread: self.thread.join(timeout=2.0)\n",
    "        with open(out_path, 'w') as f: json.dump(self.metrics, f)\n",
    "        logger.info(f'\\U0001f4c8 Métricas de Hardware guardadas en {out_path}')\n",
    "hw_monitor = HardwareMonitor()\n",
    "\n",
    "def print_tree(startpath, max_depth=3):\n",
    "    print(f'📁 Estructura de {os.path.basename(startpath)}:')\n",
    "    for root, dirs, files in os.walk(startpath):\n",
    "        level = root.replace(startpath, '').count(os.sep)\n",
    "        if level > max_depth: continue\n",
    "        indent = ' ' * 4 * level\n",
    "        print(f'{indent}📂 {os.path.basename(root)}/')\n",
    "        subindent = ' ' * 4 * (level + 1)\n",
    "        for f in files[:10]:\n",
    "            print(f'{subindent}📄 {f}')\n",
    "        if len(files) > 10: print(f'{subindent}... ({len(files)-10} más)')\n",
    "\n",
    "try:\n",
    "    from src.utils.drive_manager import DriveManager\n",
    "except ImportError:\n",
    "    print('❌ ERROR: No se pudo importar src.utils.drive_manager')\n",
    "    print(f'   - sys.path: {sys.path}')\n",
    "    if os.path.exists(os.path.join(PROJECT_ROOT, 'src')):\n",
    "        print_tree(os.path.join(PROJECT_ROOT, 'src'))\n",
    "    else:\n",
    "        print(f'❌ La carpeta src NO EXISTE en {PROJECT_ROOT}')\n",
    "    raise\n",
    "\n",
    "try:\n",
    "    from src.utils.pipeline_timer import PipelineTimer\n",
    "    timer = PipelineTimer()\n",
    "    timer.detect_hardware()\n",
    "except ImportError:\n",
    "    class DummyTimer:\n",
    "        def detect_hardware(self): pass\n",
    "        def log_config(self, c): pass\n",
    "        def step(self, name): \n",
    "            class Ctx: \n",
    "                def __enter__(self): pass\n",
    "                def __exit__(self, *a): pass\n",
    "            return Ctx()\n",
    "        def save_report(self, p): pass\n",
    "    timer = DummyTimer()\n",
    "\n",
    "LAUNCH_CONFIG = None\n",
    "RENDER_ENGINE = 'CYCLES'\n",
    "DRIVE_SERVICE = None\n",
    "DRIVE_MODELS_FOLDER_ID = None\n",
    "\n",
    "if PROJECT_ROOT:\n",
    "    config_path = os.path.join(PROJECT_ROOT, 'config_train.json')\n",
    "    if os.path.exists(config_path):\n",
    "        with open(config_path, 'r') as f: LAUNCH_CONFIG = json.load(f)\n",
    "        timer.log_config(LAUNCH_CONFIG)\n",
    "        RENDER_ENGINE = LAUNCH_CONFIG.get('render_settings', {}).get('engine', 'CYCLES').upper()\n",
    "    \n",
    "    try:\n",
    "        from src.utils.drive_manager import DriveManager\n",
    "        token_src = os.path.join(PROJECT_ROOT, 'token_1973.pickle')\n",
    "        creds_src = os.path.join(PROJECT_ROOT, 'credentials.json')\n",
    "        token_wt = os.path.join(WORKSPACE_DIR, 'token_1973.pickle')\n",
    "        creds_wt = os.path.join(WORKSPACE_DIR, 'credentials.json')\n",
    "        if not os.path.exists(token_wt) and os.path.exists(token_src): shutil.copy(token_src, token_wt)\n",
    "        if not os.path.exists(creds_wt) and os.path.exists(creds_src): shutil.copy(creds_src, creds_wt)\n",
    "        \n",
    "        if os.path.exists(token_wt):\n",
    "            dm = DriveManager(credentials_path=creds_wt, token_path=token_wt)\n",
    "            if dm.authenticate():\n",
    "                DRIVE_SERVICE = dm.service\n",
    "                root_id = dm.ensure_folder('Lego_Training_75078')\n",
    "                DRIVE_MODELS_FOLDER_ID = dm.ensure_folder('models', parent_id=root_id)\n",
    "                logger.info(f'✅ Drive autenticado: {dm.account_email}')\n",
    "    except Exception as e:\n",
    "        logger.warning(f'⚠️ Drive no disponible: {e}')\n",
    "\n",
    "logger.info(f'Pipeline v5.0 | Motor: {RENDER_ENGINE} | Root: {PROJECT_ROOT} | Workspace: {WORKSPACE_DIR}')\n"
]

# --- COLAB SETUP ---
_C0_COLAB_BODY = [
    "# =================================================================\n",
    "# CELDA 0: Setup Google Colab (v5.0)\n",
    "# =================================================================\n",
    "print('🔧 Google Colab detectado | v5.0')\n",
    "from google.colab import drive\n",
    "drive.mount('/content/drive')\n",
    "os.system('apt-get update -qq && apt-get install -y -qq libxrender1 libxext6 libgl1-mesa-glx libxi6 libxkbcommon0 libdbus-1-3 > /dev/null')\n",
    "\n",
    "# Auto-detect project root in Drive\n",
    "potential_roots = ['/content/drive/MyDrive/Lego_Training_75078', '/content/drive/MyDrive/test_heavy_image_recognition/lego_recognition_system']\n",
    "for pr in potential_roots:\n",
    "    if os.path.exists(os.path.join(pr, 'src')):\n",
    "        PROJECT_ROOT = pr\n",
    "        print(f'✅ Proyecto detectado: {PROJECT_ROOT}')\n",
    "        break\n",
    "if not PROJECT_ROOT:\n",
    "    print('🔍 Buscando src en Drive...')\n",
    "    for root, dirs, files in os.walk('/content/drive/MyDrive', topdown=True):\n",
    "        if 'src' in dirs:\n",
    "            src_path = os.path.join(root, 'src')\n",
    "            if os.path.isdir(src_path) and 'logic' in os.listdir(src_path):\n",
    "                PROJECT_ROOT = root\n",
    "                print(f'✅ Encontrado: {PROJECT_ROOT}')\n",
    "                break\n",
    "        if len(root.split(os.sep)) > 7: continue\n",
    "if not PROJECT_ROOT:\n",
    "    print('⚠️ No se encontró el proyecto. Usando ruta por defecto.')\n",
    "    PROJECT_ROOT = potential_roots[0]\n",
    "WORKSPACE_DIR = '/content/colab_workspace'\n",
    "print(f'📍 Root: {PROJECT_ROOT}')\n",
    "\n",
    "# Auto-create __init__.py files for imports from Drive\n",
    "if os.path.exists(os.path.join(PROJECT_ROOT, 'src')):\n",
    "    print('🔧 Verificando __init__.py en src/...')\n",
    "    for root, dirs, files in os.walk(os.path.join(PROJECT_ROOT, 'src')):\n",
    "        dirs[:] = [d for d in dirs if not d.startswith('.') and d != '__pycache__']\n",
    "        if '__init__.py' not in files:\n",
    "            try:\n",
    "                with open(os.path.join(root, '__init__.py'), 'w') as f: pass\n",
    "                print(f'   + Creado __init__.py en {os.path.relpath(root, PROJECT_ROOT)}')\n",
    "            except: pass\n",
]

# --- KAGGLE SETUP ---
_C0_KAGGLE_BODY = [
    "# =================================================================\n",
    "# CELDA 0: Setup Kaggle (v5.0)\n",
    "# =================================================================\n",
    "print('🔧 Kaggle detectado | v5.0')\n",
    "WORKSPACE_DIR = '/kaggle/working/kaggle_workspace'\n",
    "if not os.path.exists('/kaggle'):\n",
    "    print('⚠️ ADVERTENCIA: Entorno Kaggle NO detectado. Usando modo de compatibilidad...')\n",
    "    WORKSPACE_DIR = os.path.join(os.getcwd(), 'workspace_kaggle_fallback')\n",
    "\n",
    "# Extract project from dataset ZIP\n",
    "zip_path = next(Path('/kaggle/input').rglob('*.zip'), None)\n",
    "if zip_path:\n",
    "    tmp_proj = '/kaggle/working/proj'\n",
    "    os.makedirs(tmp_proj, exist_ok=True)\n",
    "    with zipfile.ZipFile(zip_path, 'r') as z: z.extractall(tmp_proj)\n",
    "    PROJECT_ROOT = tmp_proj\n",
    "else:\n",
    "    src_dir = next(Path('/kaggle/input').rglob('src'), None)\n",
    "    if src_dir: PROJECT_ROOT = str(src_dir.parent)\n",
    "\n",
    "# Copy credentials from Kaggle dataset\n",
    "for cred_file in ['credentials.json', 'token_1973.pickle']:\n",
    "    kaggle_cred = next(Path('/kaggle/input').rglob(cred_file), None)\n",
    "    if kaggle_cred:\n",
    "        dest = os.path.join('/kaggle/working', cred_file)\n",
    "        if not os.path.exists(dest):\n",
    "            shutil.copy(str(kaggle_cred), dest)\n",
    "            print(f'   + Copiado {cred_file} desde dataset')\n",
]

# --- LIGHTNING SETUP ---
_C0_LIGHTNING_BODY = [
    "# =================================================================\n",
    "# CELDA 0: Setup Lightning AI (v5.0)\n",
    "# =================================================================\n",
    "print('⚡ Lightning AI detectado | v5.0')\n",
    "\n",
    "# Auto-detect project root by looking for 'src' in parents\n",
    "PROJECT_ROOT = os.getcwd()\n",
    "while PROJECT_ROOT != '/' and not os.path.exists(os.path.join(PROJECT_ROOT, 'src')):\n",
    "    PROJECT_ROOT = os.path.dirname(PROJECT_ROOT)\n",
    "\n",
    "if os.path.exists(os.path.join(PROJECT_ROOT, 'src')):\n",
    "    print(f'✅ Proyecto detectado en: {PROJECT_ROOT}')\n",
    "else:\n",
    "    print('⚠️ No se encontró la carpeta src subiendo niveles. Usando cwd.')\n",
    "    PROJECT_ROOT = os.getcwd()\n",
    "\n",
    "WORKSPACE_DIR = os.path.join(os.getcwd(), 'lightning_workspace')\n",
]

def get_c0_setup(env):
    """Returns the complete C0 Setup cell for the given environment."""
    bodies = {
        'colab': _C0_COLAB_BODY,
        'kaggle': _C0_KAGGLE_BODY,
        'lightning': _C0_LIGHTNING_BODY,
    }
    return _C0_IMPORTS + bodies[env] + _C0_COMMON_TAIL


# =====================================================================
# CELL 1: INSTALL BLENDER (Shared)
# =====================================================================
C1_INSTALL = [
    "# =====================================================================\n",
    "# CELDA 1: Instalacion Blender + LDraw + Addon (v5.0)\n",
    "# =====================================================================\n",
    "logger.info('>>> FASE 1/7: Instalación de Blender y Dependencias')\n",
    "ADDON_PATH = os.path.join(WORKSPACE_DIR, 'tmp_addon')\n",
    "LDRAW_PATH = os.path.join(WORKSPACE_DIR, 'ldraw_lib')\n",
    "os.makedirs(ADDON_PATH, exist_ok=True)\n",
    "\n",
    "def download_file(url, target_path):\n",
    "    if os.path.exists(target_path): return\n",
    "    logger.info(f'Descargando {os.path.basename(target_path)}...')\n",
    "    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})\n",
    "    with urllib.request.urlopen(req) as response, open(target_path, 'wb') as out:\n",
    "        shutil.copyfileobj(response, out)\n",
    "\n",
    "with timer.step('Install Blender + Dependencies'):\n",
    "    BLENDER_PORTABLE_DIR = os.path.join(WORKSPACE_DIR, 'blender-4.2.7-linux-x64')\n",
    "    BLENDER_PATH = os.path.join(BLENDER_PORTABLE_DIR, 'blender')\n",
    "    if not os.path.exists(BLENDER_PATH):\n",
    "        logger.info('Descargando Blender 4.2 LTS Portable (EGL)...')\n",
    "        blender_tarball = os.path.join(WORKSPACE_DIR, 'blender.tar.xz')\n",
    "        download_file('https://mirror.clarkson.edu/blender/release/Blender4.2/blender-4.2.7-linux-x64.tar.xz', blender_tarball)\n",
    "        logger.info('Extrayendo Blender...')\n",
    "        subprocess.run(['tar', '-xf', blender_tarball, '-C', WORKSPACE_DIR], check=True)\n",
    "        if os.path.exists(blender_tarball): os.remove(blender_tarball)\n",
    "    os.environ['__EGL_VENDOR_LIBRARY_FILENAMES'] = '/usr/share/glvnd/egl_vendor.d/10_nvidia.json'\n",
    "    os.environ['DISPLAY'] = ''\n",
    "    logger.info(f'Blender portable listo: {BLENDER_PATH} | EGL OK')\n",
    "    \n",
    "    if not os.path.exists(LDRAW_PATH):\n",
    "        ldraw_zip = os.path.join(WORKSPACE_DIR, 'ldraw_complete.zip')\n",
    "        local_ldraw = os.path.join(PROJECT_ROOT, 'ldraw_complete.zip')\n",
    "        if os.path.exists(local_ldraw):\n",
    "            shutil.copy(local_ldraw, ldraw_zip)\n",
    "        else:\n",
    "            download_file('https://library.ldraw.org/library/updates/complete.zip', ldraw_zip)\n",
    "            \n",
    "        with zipfile.ZipFile(ldraw_zip, 'r') as z: z.extractall(f'{LDRAW_PATH}_temp')\n",
    "        temp_list = os.listdir(f'{LDRAW_PATH}_temp')\n",
    "        if len(temp_list) == 1 and temp_list[0].lower() == 'ldraw':\n",
    "            shutil.copytree(f'{LDRAW_PATH}_temp/ldraw', LDRAW_PATH, dirs_exist_ok=True)\n",
    "        else:\n",
    "            shutil.copytree(f'{LDRAW_PATH}_temp', LDRAW_PATH, dirs_exist_ok=True)\n",
    "        shutil.rmtree(f'{LDRAW_PATH}_temp')\n",
    "\n",
    "    if not os.path.exists(os.path.join(ADDON_PATH, 'io_scene_importldraw')):\n",
    "        addon_zip = os.path.join(WORKSPACE_DIR, 'importldraw.zip')\n",
    "        local_addon = os.path.join(PROJECT_ROOT, 'importldraw.zip')\n",
    "        if os.path.exists(local_addon):\n",
    "            shutil.copy(local_addon, addon_zip)\n",
    "        else:\n",
    "            download_file('https://github.com/TobyLobster/ImportLDraw/releases/download/v1.2.2/importldraw1.2.2.zip', addon_zip)\n",
    "            \n",
    "        with zipfile.ZipFile(addon_zip, 'r') as z: z.extractall(ADDON_PATH)\n",
    "        inner = [d for d in os.listdir(ADDON_PATH) if 'importldraw' in d.lower() and os.path.isdir(os.path.join(ADDON_PATH, d))][0]\n",
    "        if inner != 'io_scene_importldraw': shutil.move(os.path.join(ADDON_PATH, inner), os.path.join(ADDON_PATH, 'io_scene_importldraw'))\n",
    "\n",
    "logger.info(f'Listo. Blender={BLENDER_PATH} | LDraw={LDRAW_PATH}')\n"
]

# =====================================================================
# CELL 2: PART RESOLUTION (Shared)
# =====================================================================
C2_RESOLVE = [
    "# =====================================================================\n",
    "# CELDA 2: 🎯 Resolución de Piezas\n",
    "# =====================================================================\n",
    "logger.info('>>> FASE 2/7: Resolución de Piezas')\n",
    "import ipywidgets as widgets\n",
    "from IPython.display import display, clear_output\n",
    "from src.logic.part_resolver import resolve_set, resolve_piece\n",
    "\n",
    "RESOLVED_PARTS = []\n",
    "RENDER_ENGINE = 'EEVEE'\n",
    "NUM_IMAGES = 150\n",
    "SET_ID = \"custom\"\n",
    "\n",
    "if LAUNCH_CONFIG:\n",
    "    print(\"🚀 Usando configuración automática del Launchpad...\")\n",
    "    target_parts = LAUNCH_CONFIG.get('target_parts', [])\n",
    "    RENDER_ENGINE = LAUNCH_CONFIG.get('render_settings', {}).get('engine', 'EEVEE')\n",
    "    NUM_IMAGES = LAUNCH_CONFIG.get('render_settings', {}).get('num_images', 150)\n",
    "    SET_ID = LAUNCH_CONFIG.get('session_reference', 'custom').split('_')[0]\n",
    "    \n",
    "    mode = LAUNCH_CONFIG.get('mode', 'piece')\n",
    "    import glob\n",
    "    inv_files = glob.glob(os.path.join(PROJECT_ROOT, f'inventory_{SET_ID}*.json'))\n",
    "    if mode == 'set' or (len(target_parts) == 1 and inv_files):\n",
    "        if inv_files:\n",
    "            with open(inv_files[0], 'r') as f:\n",
    "                set_data = json.load(f)\n",
    "                target_parts = [p['part_num'] for p in set_data.get('parts', [])]\n",
    "    \n",
    "    for p_id in target_parts:\n",
    "        RESOLVED_PARTS.extend(resolve_piece(p_id))\n",
    "    \n",
    "    print(f\"   • Motor: {RENDER_ENGINE}\")\n",
    "    print(f\"   • Imágenes: {NUM_IMAGES}\")\n",
    "    print(f\"   • Piezas: {[p['ldraw_id'] for p in RESOLVED_PARTS]}\")\n",
    "else:\n",
    "    print(\"⚠️ No se detectó config_train.json. Usa el Launchpad local para configurar.\")\n",
]

# =====================================================================
# CELL 3: VERIFICATION (Shared)
# =====================================================================
C3_VERIFY = [
    "# =====================================================================\n",
    "# CELDA 3: ✅ Verificación y Filtrado\n",
    "# =====================================================================\n",
    "logger.info('>>> FASE 3/7: Verificación y Filtrado')\n",
    "from src.logic.model_registry import get_training_status, filter_pending\n",
    "\n",
    "if not RESOLVED_PARTS:\n",
    "    raise Exception(\"❌ No hay piezas para procesar.\")\n",
    "\n",
    "status_list = get_training_status(RESOLVED_PARTS, PROJECT_ROOT, drive_service=DRIVE_SERVICE, drive_models_folder_id=DRIVE_MODELS_FOLDER_ID)\n",
    "PARTS_TO_TRAIN = filter_pending(status_list)\n",
    "TARGET_PART_IDS = [p['ldraw_id'] for p in PARTS_TO_TRAIN]\n",
    "\n",
    "print(f\"─── RESUMEN DE MODELOS ───\")\n",
    "for s in status_list:\n",
    "    status = \"✅\" if s['is_complete'] else \"❌\"\n",
    "    print(f\"{status} {s['ldraw_id']}: {s['name']}\")\n",
]

# =====================================================================
# CELL 4: RENDER (Minor env differences via params)
# =====================================================================
def get_c4_render(env):
    """Returns render cell with dynamic worker count based on GPUs."""
    return [
    "# =================================================================\n",
    "# CELDA 4: Generación de Dataset (Blender Render)\n",
    "# =================================================================\n",
    "import subprocess, concurrent.futures, torch, time, psutil\n",
    "import shutil, json, os\n",
    "\n",
    "def get_piece_tier(part_id, ldraw_path, rebrickable_data):\n",
    "    score = 0\n",
    "    # 1. Análisis Semántico (Rebrickable)\n",
    "    cat = rebrickable_data.get('category', '').lower()\n",
    "    if any(x in cat for x in ['minifig', 'head', 'body', 'accessory', 'animal']):\n",
    "        return 'TIER_3'\n",
    "    if any(x in cat for x in ['brick', 'plate', 'tile']):\n",
    "        score -= 5\n",
    "    # 2. Análisis Estructural (LDRAW)\n",
    "    path = os.path.join(ldraw_path, 'parts', f'{part_id}.dat')\n",
    "    if os.path.exists(path):\n",
    "        with open(path, 'r', errors='ignore') as f:\n",
    "            lines = f.readlines()\n",
    "            subpart_calls = len([1 for l in lines if l.startswith('1')])\n",
    "        if subpart_calls > 15: score += 10\n",
    "        elif subpart_calls > 5: score += 5\n",
    "    # 3. Decisión Final\n",
    "    if score >= 10: return 'TIER_3'\n",
    "    if score >= 0: return 'TIER_2'\n",
    "    return 'TIER_1'\n",
    "\n",
    "if not PARTS_TO_TRAIN:\n",
    "    print('✅ No hay piezas pendientes de render. Saltando celda.')\n",
    "else:\n",
    "    # Determine Set Tier (Maximum of all parts) - DEPRECATED\n",
    "    # Now resolving per-piece for Universal Detection\n",
    "    pieces_config = []\n",
    "    total_images_to_render = 0\n",
    "    has_cycles = False\n",
    "    TIER_CONFIG = {\n",
    "        'TIER_1': {'imgs': 30, 'res': 640, 'engine': 'EEVEE', 'epochs': 50},\n",
    "        'TIER_2': {'imgs': 80, 'res': 1280, 'engine': 'EEVEE', 'epochs': 150},\n",
    "        'TIER_3': {'imgs': 150, 'res': 2048, 'engine': 'CYCLES', 'epochs': 300},\n",
    "    }\n",
    "    for p in PARTS_TO_TRAIN:\n",
    "        tier_str = get_piece_tier(p['ldraw_id'], LDRAW_PATH, p)\n",
    "        cfg_t = TIER_CONFIG[tier_str]\n",
    "        pieces_config.append({\n",
    "            'part': p,\n",
    "            'tier': tier_str,\n",
    "            'imgs': cfg_t['imgs'],\n",
    "            'engine': cfg_t['engine'],\n",
    "            'res': cfg_t['res']\n",
    "        })\n",
    "        total_images_to_render += cfg_t['imgs']\n",
    "        if cfg_t['engine'] == 'CYCLES': has_cycles = True\n",
    "    \n",
    "    TRAIN_EPOCHS = max([TIER_CONFIG[pc['tier']]['epochs'] for pc in pieces_config])\n",
    "    \n",
    "    print(f'\\U0001f3a8 Render Plan Agnóstico Universal: {len(pieces_config)} piezas | {total_images_to_render} imgs totales')\n",
    "    for pc in pieces_config:\n",
    "        print(f\"   • {pc['part']['ldraw_id']}: {pc['tier']} | {pc['imgs']} imgs | {pc['engine']} | {pc['res']}px\")\n",
    "    \n",
    "    # --- Blender Kernel Restoration ---\n",
    "    def restore_kernels():\n",
    "        kernel_found = False\n",
    f"        potential_dirs = ['{'/kaggle/input/blender-kernels' if env == 'kaggle' else 'os.path.join(PROJECT_ROOT)'}', PROJECT_ROOT, os.getcwd()]\n",
    "        for kernel_dir in potential_dirs:\n",
    "            if not os.path.exists(kernel_dir): continue\n",
    "            cycles_bin_path = os.path.join(kernel_dir, 'cycles_kernels.bin')\n",
    "            cycles_zip_path = os.path.join(kernel_dir, 'cycles_kernels.zip')\n",
    "            cycles_bin = cycles_zip_path if os.path.exists(cycles_zip_path) else cycles_bin_path\n",
    "            if os.path.exists(cycles_bin):\n",
    "                dest = os.path.expanduser('~/.cache/cycles')\n",
    "                os.makedirs(dest, exist_ok=True)\n",
    "                try:\n",
    "                    shutil.unpack_archive(cycles_bin, dest, 'zip')\n",
    "                    print(f'🚀 [KERNEL] Cycles Kernels inyectados desde {kernel_dir}')\n",
    "                    kernel_found = True\n",
    "                except Exception as e:\n",
    "                    print(f'❌ Error descomprimiendo Cycles Kernels: {e}')\n",
    "            optix_bin = os.path.join(kernel_dir, 'optix_cache.bin')\n",
    "            if os.path.exists(optix_bin):\n",
    f"                dest = f\"/var/tmp/OptixCache_{{os.environ.get('USER', 'root')}}\"\n",
    "                os.makedirs(dest, exist_ok=True)\n",
    "                try:\n",
    "                    shutil.unpack_archive(optix_bin, dest, 'zip')\n",
    "                    print(f'🚀 [KERNEL] OptiX Cache inyectado desde {kernel_dir}')\n",
    "                    kernel_found = True\n",
    "                except Exception as e:\n",
    "                    print(f'❌ Error descomprimiendo OptiX Cache: {e}')\n",
    "        if not kernel_found:\n",
    "            print(f'⚠️ No se encontraron kernels precompilados. Blender los compilará.')\n",
    "    if has_cycles: restore_kernels()\n",
    "\n",
    "    NUM_GPUS = torch.cuda.device_count() if torch.cuda.is_available() else 1\n",
    "    gpu_name = torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'\n",
    "    \n",
    "    # 🏎️ Worker Strategy: 2 workers per GPU (Efficiency Plan)\n",
    "    num_workers = NUM_GPUS * 2\n",
    "    \n",
    "    print(f'🔍 Hardware Detectado: {gpu_name} (x{NUM_GPUS})')\n",
    "    print(f'🚀 Estrategia de Render: {num_workers} Workers de Blender ({num_workers/NUM_GPUS:.1f}x GPU)')\n",
    "    \n",
    "    # Chunk pieces across workers logically\n",
    "    parts_chunks = [[] for _ in range(num_workers)]\n",
    "    for idx, pc in enumerate(pieces_config):\n",
    "        parts_chunks[idx % num_workers].append(pc)\n",
    "    \n",
    "    def run_render_worker(worker_id):\n",
    "        gpu_id = worker_id % NUM_GPUS\n",
    "        chunks_for_worker = parts_chunks[worker_id]\n",
    "        if not chunks_for_worker: return # Idle worker\n",
    "            \n",
    "        worker_cfg = {\n",
    "            'set_id': SET_ID, 'pieces_config': chunks_for_worker, \n",
    "            'output_base': os.path.join(DATASET_DIR, SET_ID),\n",
    "            'assets_dir': os.path.join(PROJECT_ROOT, 'assets'), 'ldraw_path': LDRAW_PATH,\n",
    "            'addon_path': ADDON_PATH\n",
    "        }\n",
    "        cfg_path = os.path.join(WORKSPACE_DIR, f'render_cfg_{worker_id}.json')\n",
    "        with open(cfg_path, 'w') as f: json.dump(worker_cfg, f)\n",
    "        env = os.environ.copy()\n",
    "        env['CUDA_VISIBLE_DEVICES'] = str(gpu_id)\n",
    "        env['OPTIX_VISIBLE_DEVICES'] = str(gpu_id)\n",
    "        env['PYTHONPATH'] = PROJECT_ROOT\n",
    "        env['UNIVERSAL_DETECTOR'] = '1'\n",
    "        log_file = os.path.join(WORKSPACE_DIR, f'worker_{worker_id}.log')\n",
    "        with open(log_file, 'w') as f_out:\n",
    "            subprocess.run([BLENDER_PATH, '--background', '--python',\n",
    "                os.path.join(PROJECT_ROOT, 'src', 'blender_scripts', 'scene_setup.py'),\n",
    "                '--', cfg_path], stdout=f_out, stderr=subprocess.STDOUT, env=env)\n",
    "\n",
    "    images_dir = os.path.join(DATASET_DIR, SET_ID, 'images')\n",
    "    labels_dir = os.path.join(DATASET_DIR, SET_ID, 'labels')\n",
    "    # ⚠️ CRITICAL: Clear old images so stale data doesn't contaminate the counter\n",
    "    if os.path.exists(images_dir): shutil.rmtree(images_dir)\n",
    "    if os.path.exists(labels_dir): shutil.rmtree(labels_dir)\n",
    "    os.makedirs(images_dir, exist_ok=True)\n",
    "    os.makedirs(labels_dir, exist_ok=True)\n",
    "    print(f'🗑️ Directorio limpiado: {images_dir}')\n",
    "\n",
    "    with timer.step('Blender Render Workers'):\n",
    "        print('🚀 INICIANDO RENDER | ' + str(num_workers) + ' Workers | ' + RENDER_ENGINE)\n",
    "        print('=' * 100)\n",
    "        hw_monitor.start()\n",
    "        start_t = time.time()\n",
    "        with concurrent.futures.ThreadPoolExecutor(max_workers=num_workers) as executor:\n",
    "            futures = [executor.submit(run_render_worker, i) for i in range(num_workers)]\n",
    "            while any(f.running() for f in futures):\n",
    "                curr_imgs = len(os.listdir(images_dir)) if os.path.exists(images_dir) else 0\n",
    "                elapsed = time.time() - start_t\n",
    "                worker_status = []\n",
    "                for i in range(num_workers):\n",
    "                    tail = 'Iniciando...' \n",
    "                    log_f = os.path.join(WORKSPACE_DIR, f'worker_{i}.log')\n",
    "                    if os.path.exists(log_f):\n",
    "                        try:\n",
    "                            with open(log_f, 'r') as f:\n",
    "                                lines = f.readlines()\n",
    "                                if lines: tail = lines[-1].strip()[-40:]\n",
    "                        except: pass\n",
    "                    worker_status.append(f'W{i}: {tail}')\n",
    "                cpu, ram = psutil.cpu_percent(), psutil.virtual_memory().percent\n",
    "                vram = torch.cuda.memory_reserved(0)/1e9 if torch.cuda.is_available() else 0\n",
    "                fps = curr_imgs/elapsed if elapsed > 0 else 0\n",
    "                pct = (curr_imgs/total_images_to_render)*100\n",
    "                print(f'[{pct:>3.0f}%] {curr_imgs}/{total_images_to_render} | {fps:.1f} FPS | CPU {cpu}% | RAM {ram}% | VRAM {vram:.1f}GB | {int(elapsed)}s')\n",
    "                for s in worker_status: print(f'  ↳ {s}')\n",
    "                print('\\033[F' * (num_workers + 2), end='', flush=True)\n",
    "                time.sleep(3)\n",
    "        hw_monitor.stop(os.path.join(WORKSPACE_DIR, 'hw_metrics_render.json'))\n",
    "        print('' * (num_workers + 1) + '=' * 100)\n",
    "        img_count = len(os.listdir(images_dir)) if os.path.exists(images_dir) else 0\n",
    "        lbl_count = len(os.listdir(labels_dir)) if os.path.exists(labels_dir) else 0\n",
    "        min_expected = max(1, total_images_to_render // 2)\n",
    "        if img_count < min_expected:\n",
    "            print(f'❌ CRITICAL: BLENDER FAILED – solo {img_count}/{total_images_to_render} imgs, {lbl_count} labels')\n",
    "            for i in range(num_workers):\n",
    "                log_f = os.path.join(WORKSPACE_DIR, f'worker_{i}.log')\n",
    "                if os.path.exists(log_f):\n",
    "                    print(f'--- LOG WORKER {i} ---')\n",
    "                    with open(log_f, 'r') as lc: print(lc.read())\n",
    "            raise RuntimeError(f'Blender render insuficiente: {img_count} imgs. Mínimo esperado: {min_expected}.')\n",
    "        else:\n",
    "            print(f'✅ Render completado: {img_count} imágenes | {lbl_count} labels')\n",
]


def get_c4_5_filter(env):
    """Returns dataset similarity filter cell."""
    return [
    "# =================================================================\n",
    "# CELDA 4.5: Filtro de Similitud (Data Pruning)\n",
    "# =================================================================\n",
    "import os, torch, numpy as np\n",
    "from PIL import Image\n",
    "from src.logic.feature_extractor import FeatureExtractor\n",
    "from glob import glob\n",
    "\n",
    "dataset_images = os.path.join(DATASET_DIR, SET_ID, 'images')\n",
    "dataset_labels = os.path.join(DATASET_DIR, SET_ID, 'labels')\n",
    "\n",
    "if not os.path.exists(dataset_images):\n",
    "    print('⚠️ No se encontró el dataset para filtrar. Saltando.')\n",
    "else:\n",
    "    img_paths = sorted(glob(os.path.join(dataset_images, '*.png')))\n",
    "    print(f'🔍 Analizando {len(img_paths)} imágenes para eliminar redundancias...')\n",
    "    \n",
    "    extractor = FeatureExtractor()\n",
    "    deleted_count = 0\n",
    "    last_embedding = None\n",
    "    \n",
    "    # Cosine Similarity threshold: 0.98\n",
    "    THRESHOLD = 0.98\n",
    "    \n",
    "    for i, path in enumerate(img_paths):\n",
    "        try:\n",
    "            # Extract embedding\n",
    "            img = Image.open(path).convert('RGB')\n",
    "            embedding = extractor.get_embedding(img)\n",
    "            # Normalize for easy cosine similarity (dot product of normalized vectors)\n",
    "            norm = np.linalg.norm(embedding)\n",
    "            if norm > 0:\n",
    "                embedding = embedding / norm\n",
    "            \n",
    "            if last_embedding is not None:\n",
    "                # Cosine similarity = dot product of normalized vectors\n",
    "                similarity = np.dot(embedding, last_embedding)\n",
    "                \n",
    "                if similarity > THRESHOLD:\n",
    "                    # Delete Image and Label\n",
    "                    os.remove(path)\n",
    "                    filename = os.path.basename(path)\n",
    "                    label_path = os.path.join(dataset_labels, filename.replace('.png', '.txt'))\n",
    "                    if os.path.exists(label_path):\n",
    "                        os.remove(label_path)\n",
    "                    deleted_count += 1\n",
    "                    continue # Don't update last_embedding if we deleted this one\n",
    "            \n",
    "            last_embedding = embedding\n",
    "            \n",
    "            if (i+1) % 100 == 0:\n",
    "                print(f'   Progreso: {i+1}/{len(img_paths)} | Eliminadas: {deleted_count}')\n",
    "                \n",
    "        except Exception as e:\n",
    "            print(f'❌ Error procesando {os.path.basename(path)}: {e}')\n",
    "            \n",
    "    print(f'✅ Filtro completado. Imágenes eliminadas: {deleted_count} ({len(img_paths) - deleted_count} restantes)')\n",
]


def get_c5_train(env):
    """Returns YOLO training cell with env-specific params."""
    workers = {'colab': 2, 'kaggle': 2, 'lightning': 4}[env]
    return [
    "# =================================================================\n",
    "# CELDA 5: YOLO Training (Stage 1 Localization)\n",
    "# =================================================================\n",
    "from ultralytics import YOLO\n",
    "import torch, time as _time\n",
    "\n",
    "if not PARTS_TO_TRAIN:\n",
    "    print('No hay piezas pendientes. Saltando entrenamiento.')\n",
    "else:\n",
    "    dataset_path = os.path.join(DATASET_DIR, SET_ID)\n",
    "    os.makedirs(dataset_path, exist_ok=True)\n",
    "    data_yaml = os.path.join(dataset_path, 'data.yaml')\n",
    "    with open(data_yaml, 'w') as f:\n",
    "        f.write(f'path: {dataset_path}\\n')\n",
    "        f.write('train: images\\n')\n",
    "        f.write('val: images\\n')\n",
    "        f.write('nc: 1\\n')\n",
    "        f.write(\"names: ['lego']\\n\")\n",
    "    print(f'✅ data.yaml en {data_yaml}')\n",
    "\n",
    "    results_dir = os.path.join(WORKSPACE_DIR, 'results')\n",
    "    base_model_path = 'yolo11s-seg.pt'\n",
    "    models_dir = os.path.join(PROJECT_ROOT, 'models', 'yolo_model')\n",
    "    os.makedirs(models_dir, exist_ok=True)\n",
    "    if os.path.exists(models_dir):\n",
    "        import glob\n",
    "        trained_weights = sorted(glob.glob(os.path.join(models_dir, 'universal_detector_*.pt')))\n",
    "        if trained_weights:\n",
    "            base_model_path = trained_weights[-1]\n",
    "            print(f'🧠 Continuar entrenamiento incremental desde: {os.path.basename(base_model_path)}')\n",
    "        else:\n",
    "            print('🌱 Iniciando entrenamiento desde base (yolo11s-seg.pt)')\n",
    "    model = YOLO(base_model_path, task='segment')\n",
    "\n",
    "    num_gpus = torch.cuda.device_count()\n",
    "    train_device = list(range(num_gpus)) if num_gpus > 1 else (0 if num_gpus == 1 else 'cpu')\n",
    "    train_batch = -1\n",
    "\n",
    "    os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'\n",
    "    torch.cuda.empty_cache()\n",
    "\n",
    "    _t_epoch = [_time.time()]\n",
    "    def _on_epoch_end(trainer):\n",
    "        elapsed = _time.time() - _t_epoch[0]\n",
    "        m = trainer.metrics or {}\n",
    "        vram = torch.cuda.memory_reserved(0)/1e9 if torch.cuda.is_available() else 0\n",
    "        print(f'[EPOCH {trainer.epoch+1}/{trainer.epochs}] {elapsed:.1f}s | Box: {m.get(\"train/box_loss\",0):.4f} | mAP50: {m.get(\"metrics/mAP50(B)\",0):.4f} | VRAM: {vram:.1f}GB', flush=True)\n",
    "    model.add_callback('on_fit_epoch_end', _on_epoch_end)\n",
    "\n",
    "    with timer.step('YOLO Training'):\n",
    "        epochs = TRAIN_EPOCHS if 'TRAIN_EPOCHS' in globals() else 150\n",
    "        print(f'🚀 Entrenamiento en dispositivos: {train_device} | Epochs: {epochs}')\n",
    "        hw_monitor.start()\n",
    "        model.train(\n",
    "            task='segment',\n",
    "            data=data_yaml,\n",
    "            epochs=epochs,\n",
    "            patience=10,\n",
    "            # imgsz matches render resolution from tier config\n",
    "            imgsz=2048 if (SET_TIER if 'SET_TIER' in globals() else '') == 'TIER_3' else 1280,\n",
    "            project=results_dir,\n",
    "            name=f'yolo11_{SET_ID}',\n",
    "            batch=train_batch,\n",
    "            device=train_device,\n",
    f"            workers={workers},\n",
    "            cache=True,\n",
    "            amp=True,\n",
    "            optimizer='auto',\n",
    "            verbose=False,\n",
    "            mosaic=1.0,\n",
    "            mixup=0.1,\n",
    "            scale=0.1,\n",
    "            perspective=0.0,\n",
    "            degrees=180.0,\n",
    "            translate=0.2,\n",
    "            hsv_s=0.7,\n",
    "            hsv_v=0.4,\n",
    "            bgr=0.2,\n",
    "            blur=0.1,\n",
    "            median_blur=0.1,\n",
    "            erasing=0.4\n",
    "        )\n",
    "        hw_monitor.stop(os.path.join(WORKSPACE_DIR, 'hw_metrics_train.json'))\n",
    "\n",
    "        # --- AUTO-VERSIONADO (FLAT IN yolo_model) ---\n",
    "        print('💾 Guardando nueva versión del modelo...')\n",
    "        import shutil, datetime, glob\n",
    "        dirs = glob.glob(os.path.join(results_dir, f'yolo11_{SET_ID}*'))\n",
    "        latest_dir = max(dirs, key=os.path.getmtime) if dirs else os.path.join(results_dir, f'yolo11_{SET_ID}')\n",
    "        best_pt_path = os.path.join(latest_dir, 'weights', 'best.pt')\n",
    "        if os.path.exists(best_pt_path):\n",
    "            timestamp = datetime.datetime.now().strftime('%Y%m%d_%H%M')\n",
    "            model_out_dir = os.path.join(PROJECT_ROOT, 'models', 'yolo_model')\n",
    "            os.makedirs(model_out_dir, exist_ok=True)\n",
    "            new_model_name = f'universal_detector_{timestamp}.pt'\n",
    "            dest_path = os.path.join(model_out_dir, new_model_name)\n",
    "            shutil.copy2(best_pt_path, dest_path)\n",
    "            print(f'✅ Modelo incremental guardado: {dest_path}')\n",
    "        else:\n",
    "            print('⚠️ No se encontró weights/best.pt')\n",
]


# =====================================================================
# CELL 6: VECTOR INDEX (Shared)
# =====================================================================
C6_INDEX = [
    "# =================================================================\n",
    "# CELDA 6: Vector Index Generation (Stage 2 Identification)\n",
    "# =================================================================\n",
    "import datetime, os, logging\n",
    "try:\n",
    "    _log = logger if 'logger' in globals() else logging.getLogger('nb')\n",
    "    from src.logic.build_reference_index import build_index\n",
    "    \n",
    "    # --- PERSISTENT PIEZAS VECTORES INDEX ---\n",
    "    dataset_path = os.path.join(DATASET_DIR, SET_ID)\n",
    "    \n",
    "    # Fixed folder aligned with user repo structure\n",
    "    indices_dir = os.path.join(PROJECT_ROOT, 'models', 'piezas_vectores')\n",
    "    os.makedirs(indices_dir, exist_ok=True)\n",
    "\n",
    "    with timer.step('Vector Index Generation'):\n",
    "        if os.path.exists(os.path.join(indices_dir, 'lego.index')):\n",
    "            print(f'➕ Actualizando índice maestro en: {indices_dir}...')\n",
    "        else:\n",
    "            print(f'🚀 Creando nuevo índice maestro en: {indices_dir}...')\n",
    "        \n",
    "        build_index(dataset_path, indices_dir, unified=True)\n",
    "        print(f'✅ Proceso completado. Total vectores: {indices_dir}/lego.index')\n",
    "except Exception as e:\n",
    "    if 'logger' in globals():\n",
    "        logger.error(f'❌ Error generando Indices: {e}')\n",
    "    else:\n",
    "        print(f'❌ Error generando Indices: {e}')\n",
]


# =====================================================================
# CELL 7: SYNC (Environment-Specific)
# =====================================================================

_C7_SHARED_HEAD = [
    "# =================================================================\n",
    "# CELDA 7: Extracción y Sincronización (v5.2)\n",
    "# =================================================================\n",
    "import os, json, zipfile, datetime, shutil, glob\n",
    "\n",
    "try:\n",
    "    # --- Robust Variable Recovery ---\n",
    "    _root = PROJECT_ROOT if 'PROJECT_ROOT' in globals() else os.getcwd()\n",
    "    _ws = WORKSPACE_DIR if 'WORKSPACE_DIR' in globals() else os.path.join(_root, 'lightning_workspace')\n",
    "    \n",
    "    _cfg = LAUNCH_CONFIG if 'LAUNCH_CONFIG' in globals() else {}\n",
    "    if not _cfg:\n",
    "        _cfg_p = os.path.join(_root, 'config_train.json')\n",
    "        if os.path.exists(_cfg_p):\n",
    "            with open(_cfg_p, 'r') as f: _cfg = json.load(f)\n",
    "    \n",
    "    _set_id = _cfg.get('session_reference', 'unknown')\n",
    "    _ts = datetime.datetime.now().strftime('%Y%m%d_%H%M')\n",
    "    _zip_name = f'pipeline_results_{_set_id}_{_ts}.zip'\n",
    "    zip_path = os.path.join(_ws, _zip_name)\n",
    "    \n",
    "    # Locate YOLO output folder - search everywhere for best.pt if needed\n",
    "    _results_dir = os.path.join(_ws, 'results')\n",
    "    _dirs = glob.glob(os.path.join(_results_dir, f'yolo11_{_set_id}*'))\n",
    "    if not _dirs: _dirs = glob.glob(os.path.join(_results_dir, 'yolo11_*'))\n",
    "    _yolo_out = max(_dirs, key=os.path.getmtime) if _dirs else os.path.join(_results_dir, f'yolo11_{_set_id}')\n",
    "    \n",
    "    _report_p = os.path.join(_ws, 'performance_report.json')\n",
    "    \n",
    "    print(f'📦 Creando informe y empaquetando resultados para {_set_id}...')\n",
    "    if 'timer' in globals(): timer.save_report(_report_p)\n",
    "    \n",
    "    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:\n",
    "        # 1. Pesos del modelo (Master YOLO folder)\n",
    "        _yolo_dir = os.path.join(_root, 'models', 'yolo_model')\n",
    "        if os.path.exists(_yolo_dir):\n",
    "            _all_pts = sorted(glob.glob(os.path.join(_yolo_dir, 'universal_detector_*.pt')))\n",
    "            if _all_pts:\n",
    "                _latest_pt = _all_pts[-1]\n",
    "                zipf.write(_latest_pt, arcname=f'yolo_model/{os.path.basename(_latest_pt)}')\n",
    "                print(f'   + Master Model included: {os.path.basename(_latest_pt)}')\n",
    "        \n",
    "        # 2. ÍNDICE MAESTRO (piezas_vectores folder)\n",
    "        _idx_dir = os.path.join(_root, 'models', 'piezas_vectores')\n",
    "        if os.path.exists(_idx_dir):\n",
    "            for _f in os.listdir(_idx_dir):\n",
    "                if _f.endswith(('.index', '.pkl')):\n",
    "                     zipf.write(os.path.join(_idx_dir, _f), arcname=f'piezas_vectores/{_f}')\n",
    "            print(f'   + Master Pieces Vector included!')\n",
    "\n",
    "        # 3. Metadatos de Entrenamiento (image_meta.jsonl)\n",
    "        _dataset_path = os.path.join(_ws, 'datasets', _set_id)\n",
    "        _meta_f = os.path.join(_dataset_path, 'image_meta.jsonl')\n",
    "        if os.path.exists(_meta_f):\n",
    "            zipf.write(_meta_f, arcname='image_meta.jsonl')\n",
    "\n",
    "        # 4. Métricas, Logs y Reporte\n",
    "        if os.path.exists(_report_p): zipf.write(_report_p, arcname='logs/performance_report.json')\n",
    "        _log_f = LOG_FILE_PATH if 'LOG_FILE_PATH' in globals() else os.path.join(_ws, 'pipeline_exec.log')\n",
    "        if os.path.exists(_log_f): zipf.write(_log_f, arcname='logs/pipeline_exec.log')\n",
    "        for hw_f in glob.glob(os.path.join(_ws, 'hw_metrics_*.json')):\n",
    "            zipf.write(hw_f, arcname=f'logs/{os.path.basename(hw_f)}')\n",
    "        for w_log in glob.glob(os.path.join(_ws, 'worker_*.log')):\n",
    "            zipf.write(w_log, arcname=f'logs/{os.path.basename(w_log)}')\n",
    "        \n",
    "        # 5. Métricas detalladas de YOLO\n",
    "        if os.path.exists(_yolo_out):\n",
    "            for root, dirs, files in os.walk(_yolo_out):\n",
    "                if 'weights' in dirs: dirs.remove('weights')\n",
    "                for file in files:\n",
    "                    fp = os.path.join(root, file)\n",
    "                    zipf.write(fp, arcname=f'yolo_metrics/{os.path.relpath(fp, _yolo_out)}')\n",
    "                    \n",
    "    print(f'✅ ZIP Creado: {zip_path}')\n",
]

_C7_COLAB_TAIL = [
    "\n",
    "    # --- Colab: Upload to Drive ---\n",
    "    _colab_drive_dest = f'{_root}/models/{_zip_name}'\n",
    "    try:\n",
    "        os.makedirs(os.path.dirname(_colab_drive_dest), exist_ok=True)\n",
    "        shutil.copy2(zip_path, _colab_drive_dest)\n",
    "        logger.info(f'✅ ZIP copiado a Drive: {_colab_drive_dest}')\n",
    "    except Exception as e:\n",
    "        logger.warning(f'⚠️ Error copiando a Drive: {e}')\n",
    "    \n",
    "    if DRIVE_SERVICE and DRIVE_MODELS_FOLDER_ID:\n",
    "        try:\n",
    "            from src.utils.drive_manager import DriveManager\n",
    "            _creds_wt = os.path.join(_ws, 'credentials.json')\n",
    "            _token_wt = os.path.join(_ws, 'token_1973.pickle')\n",
    "            if os.path.exists(_creds_wt) and os.path.exists(_token_wt):\n",
    "                _dm = DriveManager(credentials_path=_creds_wt, token_path=_token_wt)\n",
    "                if _dm.authenticate():\n",
    "                    _dm.upload_file(zip_path, DRIVE_MODELS_FOLDER_ID, overwrite=True)\n",
    "                    logger.info(f'✅ ZIP subido via API')\n",
    "        except Exception as e:\n",
    "            logger.warning(f'⚠️ Drive API error: {e}')\n",
    "    \n",
    "except Exception as e:\n",
    "    logger.error(f'❌ Error creando ZIP: {e}')\n",
]

_C7_KAGGLE_TAIL = [
    "\n",
    "    # --- Kaggle: Copy to /kaggle/working for download ---\n",
    "    logger.info('⬇️ Descarga el ZIP desde la pestaña \"Output\" de Kaggle')\n",
    "    if _ws != '/kaggle/working':\n",
    "        shutil.copy2(zip_path, f'/kaggle/working/{_zip_name}')\n",
    "    \n",
    "    # Upload via Drive API if credentials available\n",
    "    try:\n",
    "        from src.utils.drive_manager import DriveManager\n",
    "        _creds_wt = os.path.join('/kaggle/working', 'credentials.json')\n",
    "        _token_wt = os.path.join('/kaggle/working', 'token_1973.pickle')\n",
    "        if os.path.exists(_creds_wt) and os.path.exists(_token_wt):\n",
    "            _dm = DriveManager(credentials_path=_creds_wt, token_path=_token_wt)\n",
    "            if _dm.authenticate():\n",
    "                _root_id = _dm.ensure_folder('Lego_Training_75078')\n",
    "                _models_id = _dm.ensure_folder('models', parent_id=_root_id)\n",
    "                _dm.upload_file(zip_path, _models_id, overwrite=True)\n",
    "                logger.info(f'✅ ZIP subido a Drive via API')\n",
    "    except Exception as e:\n",
    "        logger.warning(f'⚠️ Drive API: {e}')\n",
    "\n",
    "except Exception as e:\n",
    "    logger.error(f'❌ Error creando ZIP: {e}')\n",
]

_C7_LIGHTNING_TAIL = [
    "\n",
    "    # --- Lightning: Copy artifacts to local Studio directories ---\n",
    "    import glob as _glob\n",
    "    _ts_save = datetime.datetime.now().strftime('%Y%m%d_%H%M')\n",
    "\n",
    "    # 1. Copy model to models/yolo_model/{ts}/\n",
    "    _yolo_local_dir = os.path.join(_root, 'models', 'yolo_model', _ts_save)\n",
    "    os.makedirs(_yolo_local_dir, exist_ok=True)\n",
    "    _best_pt = os.path.join(_yolo_out, 'weights', 'best.pt')\n",
    "    if os.path.exists(_best_pt):\n",
    "        _model_dest = os.path.join(_yolo_local_dir, f'universal_detector_{_ts_save}.pt')\n",
    "        shutil.copy2(_best_pt, _model_dest)\n",
    "        logger.info(f'✅ Modelo → {_model_dest}')\n",
    "\n",
    "    # 2. Copy vector indices to models/vector_index/{ts}/\n",
    "    _idx_local_dir = os.path.join(_root, 'models', 'vector_index', _ts_save)\n",
    "    os.makedirs(_idx_local_dir, exist_ok=True)\n",
    "    _shared_idx_dir = os.path.join(_root, 'models', 'vector_index')\n",
    "    # pick the latest timestamp sub-folder produced by C6\n",
    "    _idx_folders = sorted(_glob.glob(os.path.join(_shared_idx_dir, '*')), reverse=True)\n",
    "    _latest_idx = _idx_folders[0] if _idx_folders and os.path.isdir(_idx_folders[0]) else None\n",
    "    if _latest_idx and _latest_idx != _idx_local_dir:\n",
    "        for _f in os.listdir(_latest_idx):\n",
    "            shutil.copy2(os.path.join(_latest_idx, _f), os.path.join(_idx_local_dir, _f))\n",
    "        logger.info(f'✅ Indices → {_idx_local_dir}')\n",
    "\n",
    "    # 3. Upload ZIP to Drive\n",
    "    try:\n",
    "        from src.utils.drive_manager import DriveManager\n",
    "        _creds_wt = os.path.join(_ws, 'credentials.json')\n",
    "        _token_wt = os.path.join(_ws, 'token_1973.pickle')\n",
    "        if os.path.exists(_creds_wt) and os.path.exists(_token_wt):\n",
    "            _dm = DriveManager(credentials_path=_creds_wt, token_path=_token_wt)\n",
    "            if _dm.authenticate():\n",
    "                _root_id = _dm.ensure_folder('Lego_Training_75078')\n",
    "                _models_id = _dm.ensure_folder('models', parent_id=_root_id)\n",
    "                _dm.upload_file(zip_path, _models_id, overwrite=True)\n",
    "                logger.info(f'✅ ZIP subido a Drive via API')\n",
    "    except Exception as e:\n",
    "        logger.warning(f'⚠️ Drive API: {e}')\n",
    "    \n",
    "except Exception as e:\n",
    "    logger.error(f'❌ Error creando ZIP: {e}')\n",
]


def get_c7_sync(env):
    """Returns the complete C7 Sync cell for the given environment."""
    tails = {
        'colab': _C7_COLAB_TAIL,
        'kaggle': _C7_KAGGLE_TAIL,
        'lightning': _C7_LIGHTNING_TAIL,
    }
    return _C7_SHARED_HEAD + tails[env]
